<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Ximdex' => array($baseDir . '/lib'),
    'Solarium\\' => array($vendorDir . '/solarium/solarium/library'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
);
