<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Zend\\Stdlib\\' => array($vendorDir . '/zendframework/zend-stdlib'),
    'Zend\\EventManager\\' => array($vendorDir . '/zendframework/zend-eventmanager'),
    'Zend\\Code\\' => array($vendorDir . '/zendframework/zend-code'),
    'Ximdex' => array($baseDir . '/lib'),
    'UnitTests\\' => array($vendorDir . '/mnapoli/php-di/tests'),
    'UnitTest' => array($vendorDir . '/mnapoli/phpdocreader/tests'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Stolz\\Assets' => array($vendorDir . '/stolz/assets/src'),
    'Solarium\\' => array($vendorDir . '/solarium/solarium/library'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'PhpDocReader' => array($vendorDir . '/mnapoli/phpdocreader/src'),
    'MyCLabs' => array($vendorDir . '/myclabs/php-enum/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'JsMin' => array($vendorDir . '/werkint/jsmin'),
    'IntegrationTests\\' => array($vendorDir . '/mnapoli/php-di/tests'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'DI\\' => array($vendorDir . '/mnapoli/php-di/src'),
);
