<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('ensure that web installer works');
if(file_exists('conf/_STATUSFILE')){
    $I->deleteFile('conf/_STATUSFILE');
}
$I->amOnPage('/');
$I->see('Ximdex CMS\'s web installer');
$I->see('Check configuration', 'button');
$I->click('Check configuration');
$I->wait(2);
//$I->waitForText('Start installation', 5, 'button');
$I->see('Start installation', 'button');
$I->click('Start installation');
$I->waitForText('Installing Database',5);
$I->fillField('host', 'localhost');
$I->fillField('port', '3306');
$I->fillField('root_user', 'root');
$I->fillField('root_pass', 'ximdex');
$I->fillField('name', 'ximdex');
$I->see('Create Database', 'button');
$I->click('Create Database');
$I->wait(2);
$overwrite_message = $I->grabTextFrom('p.warning');
echo $overwrite_message;
if($overwrite_message == "ximdex database already exists. Overwrite it?"){
    $I->click('Overwrite database');
}
$I->wait(10);
$I->see('Installing Database');
$I->see('Add user', 'button');
$I->fillField('user', 'ximdex');
$I->fillField('pass', 'ximdex');
$I->click('Add user');
$I->waitForText('Settings',5);
$I->see('Save settings','button');
$I->fillField('pass', 'ximdex');
$I->click('Save settings');
$I->waitForText('Installing Ximdex CMS\'s default modules',5);
$I->waitForText('Xtags',5);
$I->see('Xtour');
$I->see('Xnews');
$I->see('Xpublish');
$I->see('Xowl');
$I->see('Install modules','button');
$I->click('Install modules');
//$I->wait(30);
$I->waitForText('Xowl configuration (optional)', 40);
$I->see('Continue','button');
$I->click('Continue');
$I->waitForText('Installation finished!',10);
$I->see('Get started', 'button');
$I->click('Get started');
$I->waitForText('User',10);
$I->see('Password');
$I->see('Sign in');
$I->fillField('user', 'ximdex');
$I->fillField('password', 'ximdex');
$I->click('Sign in');
$I->waitForText('Welcome to Ximdex CMS',5);