ALTER TABLE NodeFrames DROP FOREIGN KEY NodeFrames_Nodes;
ALTER TABLE NodeFrames DROP FOREIGN KEY NodeFrames_Versions;
ALTER TABLE `NodeFrames` CHANGE `NodeId` `NodeId` INT(12) UNSIGNED NOT NULL DEFAULT '0', 
    CHANGE `VersionId` `VersionId` INT(12) UNSIGNED NOT NULL DEFAULT '0', CHANGE `Active` `Active` INT(12) UNSIGNED NOT NULL DEFAULT '0', 
    CHANGE `IsProcessUp` `IsProcessUp` INT(12) NOT NULL DEFAULT '0', CHANGE `IsProcessDown` `IsProcessDown` INT(12) NOT NULL DEFAULT '0';
ALTER TABLE `NodeFrames` ADD CONSTRAINT `NodeFrames_nodes` FOREIGN KEY (`NodeId`) REFERENCES `Nodes`(`IdNode`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `NodeFrames` ADD CONSTRAINT `NodeFrames_Versions` FOREIGN KEY (`VersionId`) 
    REFERENCES `Versions`(`IdVersion`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `NodeFrames` CHANGE `GetActivityFrom` `GetActivityFrom` INT(12) UNSIGNED NOT NULL DEFAULT 0, 
    CHANGE `IsProcessUp` `IsProcessUp` INT(12) UNSIGNED NOT NULL DEFAULT '0', 
    CHANGE `IsProcessDown` `IsProcessDown` INT(12) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `NodeFrames` CHANGE `TimeUp` `TimeUp` INT(12) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `NodeFrames` ADD `IdPortalFrame` INT(12) UNSIGNED NOT NULL AFTER `Name`;
ALTER TABLE `NodeFrames` ADD CONSTRAINT `NodeFrames_PortalFrames` FOREIGN KEY (`IdPortalFrame`) 
    REFERENCES `PortalFrames`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
