ALTER TABLE `Channels` ADD CONSTRAINT `Channels_Nodes` FOREIGN KEY (`IdChannel`) REFERENCES `Nodes`(`IdNode`) 
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Languages` ADD CONSTRAINT `Languages_Nodes` FOREIGN KEY (`IdLanguage`) REFERENCES `Nodes`(`IdNode`) 
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Links ENGINE = InnoDB;

ALTER TABLE `Links` ADD CONSTRAINT `Links_Nodes` FOREIGN KEY (`IdLink`) REFERENCES `Nodes`(`IdNode`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Channels` CHANGE `Name` `Name` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, 
CHANGE `Description` `Description` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE `NodesToPublish` ADD `UseCache` BOOLEAN NOT NULL DEFAULT TRUE;
