// Generated by CoffeeScript 1.8.0
angular.module("ximdex.module.xmodifystates", ["ui.sortable", 'ngAnimate']).controller("XModifyStatesCtrl", [
  "$scope", "$http", "xUrlHelper", "$timeout", "$window", function($scope, $http, xUrlHelper, $timeout, $window) {
    var url;
    url = xUrlHelper.getAction({
      action: 'modifystates',
      method: 'update_states'
    });
    $scope.toDelete = [];
    $scope.thereAreMessages = false;
    $scope.sortableOptions = {
      axis: 'y',
      items: 'li.sortable',
      handle: '.sortable_element'
    };
    $scope.addStatus = function(index) {
      var n;
      n = {
        id: null,
        name: "",
        description: ""
      };
      return $scope.all_status_info.splice(index + 1, 0, n);
    };
    $scope.deleteStatus = function(index) {
      return $scope.toDelete.push($scope.all_status_info.splice(index, 1)[0]);
    };
    return $scope.saveChanges = function() {
      var petition;
      $scope.loading = true;
      petition = $http.post(url, {
        states: $scope.all_status_info,
        idNode: $scope.idNode,
        toDelete: $scope.toDelete
      });
      petition.success(function(data, status, headers, config) {
        $scope.loading = false;
        if (data.result === "ok") {
          $scope.all_status_info = JSON.parse(data.all_status_info);
          $scope.toDelete = [];
          $window.com.ximdex.widgetsVars.bw1.element.browserwindow("emptyActionsCache");
        }
        if (data.message !== "") {
          $scope.messageClass = data.result === "ok" ? "message-success" : "message-error";
          $scope.thereAreMessages = true;
          $scope.message = data.message;
          return $timeout(function() {
            $scope.thereAreMessages = false;
            return $timeout(function() {
              return $scope.message = "";
            }, 500);
          }, 2000);
        }
      });
      return petition.error(function(data, status, headers, config) {
        return $scope.loading = false;
      });
    };
  }
]);
