// Generated by CoffeeScript 1.8.0
angular.module("ximdex.main.controller").controller("XUserMenuCtrl", [
  "$scope", "xTabs", function($scope, xTabs) {
    $scope.changeLang = function(langCode, langTitle) {
      var action, nodes;
      action = {
        command: "changelang",
        name: langTitle,
        params: [
          {
            code: langCode
          }
        ]
      };
      nodes = [
        {
          nodeid: "10000"
        }
      ];
      xTabs.pushTab(action, nodes);
    };
    $scope.modifyAccount = function(userId, tabTitle) {
      var action, nodes;
      action = {
        command: "modifyuser",
        method: "index",
        name: tabTitle
      };
      nodes = [
        {
          nodeid: userId
        }
      ];
      xTabs.pushTab(action, nodes);
    };
  }
]);
