// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ContentTools.AnchoredDialogUI = (function(superClass) {
  extend(AnchoredDialogUI, superClass);

  function AnchoredDialogUI() {
    AnchoredDialogUI.__super__.constructor.call(this);
    this._position = [0, 0];
  }

  AnchoredDialogUI.prototype.mount = function() {
    this._domElement = this.constructor.createDiv(['ct-widget', 'ct-anchored-dialog']);
    this.parent().domElement().appendChild(this._domElement);
    this._domElement.style.top = this._position[1] + "px";
    return this._domElement.style.left = this._position[0] + "px";
  };

  AnchoredDialogUI.prototype.position = function(newPosition) {
    if (newPosition === void 0) {
      return this._position.slice();
    }
    this._position = newPosition.slice();
    if (this.isMounted()) {
      this._domElement.style.top = this._position[1] + "px";
      return this._domElement.style.left = this._position[0] + "px";
    }
  };

  return AnchoredDialogUI;

})(ContentTools.WidgetUI);

ContentTools.DialogUI = (function(superClass) {
  extend(DialogUI, superClass);

  function DialogUI(caption) {
    if (caption == null) {
      caption = '';
    }
    DialogUI.__super__.constructor.call(this);
    this._busy = false;
    this._caption = caption;
  }

  DialogUI.prototype.busy = function(busy) {
    if (busy === void 0) {
      return this._busy;
    }
    if (this._busy === busy) {
      return;
    }
    this._busy = busy;
    if (!this.isMounted()) {
      return;
    }
    if (this._busy) {
      return ContentEdit.addCSSClass(this._domElement, 'ct-dialog--busy');
    } else {
      return ContentEdit.removeCSSClass(this._domElement, 'ct-dialog--busy');
    }
  };

  DialogUI.prototype.caption = function(caption) {
    if (caption === void 0) {
      return this._caption;
    }
    this._caption = caption;
    return this._domCaption.textContent = ContentEdit._(caption);
  };

  DialogUI.prototype.mount = function() {
    var dialogCSSClasses, domBody, domHeader;
    dialogCSSClasses = ['ct-widget', 'ct-dialog'];
    if (this._busy) {
      dialogCSSClasses.push('ct-dialog--busy');
    }
    this._domElement = this.constructor.createDiv(dialogCSSClasses);
    this.parent().domElement().appendChild(this._domElement);
    domHeader = this.constructor.createDiv(['ct-dialog__header']);
    this._domElement.appendChild(domHeader);
    this._domCaption = this.constructor.createDiv(['ct-dialog__caption']);
    domHeader.appendChild(this._domCaption);
    this.caption(this._caption);
    this._domClose = this.constructor.createDiv(['ct-dialog__close']);
    domHeader.appendChild(this._domClose);
    domBody = this.constructor.createDiv(['ct-dialog__body']);
    this._domElement.appendChild(domBody);
    this._domView = this.constructor.createDiv(['ct-dialog__view']);
    domBody.appendChild(this._domView);
    this._domControls = this.constructor.createDiv(['ct-dialog__controls']);
    domBody.appendChild(this._domControls);
    this._domBusy = this.constructor.createDiv(['ct-dialog__busy']);
    return this._domElement.appendChild(this._domBusy);
  };

  DialogUI.prototype.unmount = function() {
    DialogUI.__super__.unmount.call(this);
    this._domBusy = null;
    this._domCaption = null;
    this._domClose = null;
    this._domControls = null;
    return this._domView = null;
  };

  DialogUI.prototype._addDOMEventListeners = function() {
    this._handleEscape = (function(_this) {
      return function(ev) {
        if (_this._busy) {
          return;
        }
        if (ev.keyCode === 27) {
          return _this.trigger('cancel');
        }
      };
    })(this);
    document.addEventListener('keyup', this._handleEscape);
    return this._domClose.addEventListener('click', (function(_this) {
      return function(ev) {
        ev.preventDefault();
        if (_this._busy) {
          return;
        }
        return _this.trigger('cancel');
      };
    })(this));
  };

  DialogUI.prototype._removeDOMEventListeners = function() {
    return document.removeEventListener('keyup', this._handleEscape);
  };

  return DialogUI;

})(ContentTools.WidgetUI);
