// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ContentTools.LinkDialog = (function(superClass) {
  var NEW_WINDOW_TARGET;

  extend(LinkDialog, superClass);

  NEW_WINDOW_TARGET = '_blank';

  function LinkDialog(href, target) {
    if (href == null) {
      href = '';
    }
    if (target == null) {
      target = '';
    }
    LinkDialog.__super__.constructor.call(this);
    this._href = href;
    this._target = target;
  }

  LinkDialog.prototype.mount = function() {
    LinkDialog.__super__.mount.call(this);
    this._domInput = document.createElement('input');
    this._domInput.setAttribute('class', 'ct-anchored-dialog__input');
    this._domInput.setAttribute('name', 'href');
    this._domInput.setAttribute('placeholder', ContentEdit._('Enter a link') + '...');
    this._domInput.setAttribute('type', 'text');
    this._domInput.setAttribute('value', this._href);
    this._domElement.appendChild(this._domInput);
    this._domTargetButton = this.constructor.createDiv(['ct-anchored-dialog__target-button']);
    this._domElement.appendChild(this._domTargetButton);
    if (this._target === NEW_WINDOW_TARGET) {
      ContentEdit.addCSSClass(this._domTargetButton, 'ct-anchored-dialog__target-button--active');
    }
    this._domButton = this.constructor.createDiv(['ct-anchored-dialog__button']);
    this._domElement.appendChild(this._domButton);
    return this._addDOMEventListeners();
  };

  LinkDialog.prototype.save = function() {
    var linkAttr;
    if (!this.isMounted) {
      return this.trigger('save', '');
    }
    linkAttr = {};
    linkAttr.href = this._domInput.value.trim();
    if (this._target) {
      linkAttr.target = this._target;
    }
    return this.trigger('save', linkAttr);
  };

  LinkDialog.prototype.show = function() {
    LinkDialog.__super__.show.call(this);
    this._domInput.focus();
    if (this._href) {
      return this._domInput.select();
    }
  };

  LinkDialog.prototype.unmount = function() {
    if (this.isMounted()) {
      this._domInput.blur();
    }
    LinkDialog.__super__.unmount.call(this);
    this._domButton = null;
    return this._domInput = null;
  };

  LinkDialog.prototype._addDOMEventListeners = function() {
    this._domInput.addEventListener('keypress', (function(_this) {
      return function(ev) {
        if (ev.keyCode === 13) {
          return _this.save();
        }
      };
    })(this));
    this._domTargetButton.addEventListener('click', (function(_this) {
      return function(ev) {
        ev.preventDefault();
        if (_this._target === NEW_WINDOW_TARGET) {
          _this._target = '';
          return ContentEdit.removeCSSClass(_this._domTargetButton, 'ct-anchored-dialog__target-button--active');
        } else {
          _this._target = NEW_WINDOW_TARGET;
          return ContentEdit.addCSSClass(_this._domTargetButton, 'ct-anchored-dialog__target-button--active');
        }
      };
    })(this));
    return this._domButton.addEventListener('click', (function(_this) {
      return function(ev) {
        ev.preventDefault();
        return _this.save();
      };
    })(this));
  };

  return LinkDialog;

})(ContentTools.AnchoredDialogUI);
