// Generated by CoffeeScript 1.10.0
var AttributeUI, StyleUI,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ContentTools.PropertiesDialog = (function(superClass) {
  extend(PropertiesDialog, superClass);

  function PropertiesDialog(element1) {
    var ref;
    this.element = element1;
    PropertiesDialog.__super__.constructor.call(this, 'Properties');
    this._attributeUIs = [];
    this._focusedAttributeUI = null;
    this._styleUIs = [];
    this._supportsCoding = this.element.content;
    if ((ref = this.element.type()) === 'ListItem' || ref === 'TableCell') {
      this._supportsCoding = true;
    }
  }

  PropertiesDialog.prototype.caption = function(caption) {
    if (caption === void 0) {
      return this._caption;
    }
    this._caption = caption;
    return this._domCaption.textContent = ContentEdit._(caption) + (": " + (this.element.tagName()));
  };

  PropertiesDialog.prototype.changedAttributes = function() {
    var attributeUI, attributes, changedAttributes, i, len, name, ref, ref1, restricted, value;
    attributes = {};
    changedAttributes = {};
    ref = this._attributeUIs;
    for (i = 0, len = ref.length; i < len; i++) {
      attributeUI = ref[i];
      name = attributeUI.name();
      value = attributeUI.value();
      if (name === '') {
        continue;
      }
      attributes[name.toLowerCase()] = true;
      if (this.element.attr(name) !== value) {
        changedAttributes[name] = value;
      }
    }
    restricted = ContentTools.getRestrictedAtributes(this.element.tagName());
    ref1 = this.element.attributes();
    for (name in ref1) {
      value = ref1[name];
      if (restricted && restricted.indexOf(name.toLowerCase()) !== -1) {
        continue;
      }
      if (attributes[name] === void 0) {
        changedAttributes[name] = null;
      }
    }
    return changedAttributes;
  };

  PropertiesDialog.prototype.changedStyles = function() {
    var cssClass, i, len, ref, styleUI, styles;
    styles = {};
    ref = this._styleUIs;
    for (i = 0, len = ref.length; i < len; i++) {
      styleUI = ref[i];
      cssClass = styleUI.style.cssClass();
      if (this.element.hasCSSClass(cssClass) !== styleUI.applied()) {
        styles[cssClass] = styleUI.applied();
      }
    }
    return styles;
  };

  PropertiesDialog.prototype.getElementInnerHTML = function() {
    if (!this._supportsCoding) {
      return null;
    }
    if (this.element.content) {
      return this.element.content.html();
    }
    return this.element.children[0].content.html();
  };

  PropertiesDialog.prototype.mount = function() {
    var attributeNames, attributes, domActions, domTabs, i, j, lastTab, len, len1, name, ref, restricted, style, styleUI, value;
    PropertiesDialog.__super__.mount.call(this);
    ContentEdit.addCSSClass(this._domElement, 'ct-properties-dialog');
    ContentEdit.addCSSClass(this._domView, 'ct-properties-dialog__view');
    this._domStyles = this.constructor.createDiv(['ct-properties-dialog__styles']);
    this._domStyles.setAttribute('data-ct-empty', ContentEdit._('No styles available for this tag'));
    this._domView.appendChild(this._domStyles);
    ref = ContentTools.StylePalette.styles(this.element.tagName());
    for (i = 0, len = ref.length; i < len; i++) {
      style = ref[i];
      styleUI = new StyleUI(style, this.element.hasCSSClass(style.cssClass()));
      this._styleUIs.push(styleUI);
      styleUI.mount(this._domStyles);
    }
    this._domAttributes = this.constructor.createDiv(['ct-properties-dialog__attributes']);
    this._domView.appendChild(this._domAttributes);
    restricted = ContentTools.getRestrictedAtributes(this.element.tagName());
    attributes = this.element.attributes();
    attributeNames = [];
    for (name in attributes) {
      value = attributes[name];
      if (restricted && restricted.indexOf(name.toLowerCase()) !== -1) {
        continue;
      }
      attributeNames.push(name);
    }
    attributeNames.sort();
    for (j = 0, len1 = attributeNames.length; j < len1; j++) {
      name = attributeNames[j];
      value = attributes[name];
      this._addAttributeUI(name, value);
    }
    this._addAttributeUI('', '');
    this._domCode = this.constructor.createDiv(['ct-properties-dialog__code']);
    this._domView.appendChild(this._domCode);
    this._domInnerHTML = document.createElement('textarea');
    this._domInnerHTML.setAttribute('class', 'ct-properties-dialog__inner-html');
    this._domInnerHTML.setAttribute('name', 'code');
    this._domInnerHTML.value = this.getElementInnerHTML();
    this._domCode.appendChild(this._domInnerHTML);
    domTabs = this.constructor.createDiv(['ct-control-group', 'ct-control-group--left']);
    this._domControls.appendChild(domTabs);
    this._domStylesTab = this.constructor.createDiv(['ct-control', 'ct-control--icon', 'ct-control--styles']);
    this._domStylesTab.setAttribute('data-tooltip', ContentEdit._('Styles'));
    domTabs.appendChild(this._domStylesTab);
    this._domAttributesTab = this.constructor.createDiv(['ct-control', 'ct-control--icon', 'ct-control--attributes']);
    this._domAttributesTab.setAttribute('data-tooltip', ContentEdit._('Attributes'));
    domTabs.appendChild(this._domAttributesTab);
    this._domCodeTab = this.constructor.createDiv(['ct-control', 'ct-control--icon', 'ct-control--code']);
    this._domCodeTab.setAttribute('data-tooltip', ContentEdit._('Code'));
    domTabs.appendChild(this._domCodeTab);
    if (!this._supportsCoding) {
      ContentEdit.addCSSClass(this._domCodeTab, 'ct-control--muted');
    }
    this._domRemoveAttribute = this.constructor.createDiv(['ct-control', 'ct-control--icon', 'ct-control--remove', 'ct-control--muted']);
    this._domRemoveAttribute.setAttribute('data-tooltip', ContentEdit._('Remove'));
    domTabs.appendChild(this._domRemoveAttribute);
    domActions = this.constructor.createDiv(['ct-control-group', 'ct-control-group--right']);
    this._domControls.appendChild(domActions);
    this._domApply = this.constructor.createDiv(['ct-control', 'ct-control--text', 'ct-control--apply']);
    this._domApply.textContent = ContentEdit._('Apply');
    domActions.appendChild(this._domApply);
    lastTab = window.localStorage.getItem('ct-properties-dialog-tab');
    if (lastTab === 'attributes') {
      ContentEdit.addCSSClass(this._domElement, 'ct-properties-dialog--attributes');
      ContentEdit.addCSSClass(this._domAttributesTab, 'ct-control--active');
    } else if (lastTab === 'code' && this._supportsCoding) {
      ContentEdit.addCSSClass(this._domElement, 'ct-properties-dialog--code');
      ContentEdit.addCSSClass(this._domCodeTab, 'ct-control--active');
    } else {
      ContentEdit.addCSSClass(this._domElement, 'ct-properties-dialog--styles');
      ContentEdit.addCSSClass(this._domStylesTab, 'ct-control--active');
    }
    return this._addDOMEventListeners();
  };

  PropertiesDialog.prototype.save = function() {
    var innerHTML;
    innerHTML = null;
    if (this._supportsCoding) {
      innerHTML = this._domInnerHTML.value;
    }
    return this.trigger('save', this.changedAttributes(), this.changedStyles(), innerHTML);
  };

  PropertiesDialog.prototype._addAttributeUI = function(name, value) {
    var attributeUI, dialog;
    dialog = this;
    attributeUI = new AttributeUI(name, value);
    this._attributeUIs.push(attributeUI);
    attributeUI.bind('blur', function() {
      var index, lastAttributeUI, length;
      dialog._focusedAttributeUI = null;
      ContentEdit.addCSSClass(dialog._domRemoveAttribute, 'ct-control--muted');
      index = dialog._attributeUIs.indexOf(this);
      length = dialog._attributeUIs.length;
      if (this.name() === '' && index < (length - 1)) {
        this.unmount();
        dialog._attributeUIs.splice(index, 1);
      }
      lastAttributeUI = dialog._attributeUIs[length - 1];
      if (lastAttributeUI) {
        if (lastAttributeUI.name() && lastAttributeUI.value()) {
          return dialog._addAttributeUI('', '');
        }
      }
    });
    attributeUI.bind('focus', function() {
      dialog._focusedAttributeUI = this;
      return ContentEdit.removeCSSClass(dialog._domRemoveAttribute, 'ct-control--muted');
    });
    attributeUI.bind('namechange', function() {
      var element, i, len, otherAttributeUI, ref, restricted, valid;
      element = dialog.element;
      name = this.name().toLowerCase();
      restricted = ContentTools.getRestrictedAtributes(element.tagName());
      valid = true;
      if (restricted && restricted.indexOf(name) !== -1) {
        valid = false;
      }
      ref = dialog._attributeUIs;
      for (i = 0, len = ref.length; i < len; i++) {
        otherAttributeUI = ref[i];
        if (name === '') {
          continue;
        }
        if (otherAttributeUI === this) {
          continue;
        }
        if (otherAttributeUI.name().toLowerCase() !== name) {
          continue;
        }
        valid = false;
      }
      this.valid(valid);
      if (valid) {
        return ContentEdit.removeCSSClass(dialog._domApply, 'ct-control--muted');
      } else {
        return ContentEdit.addCSSClass(dialog._domApply, 'ct-control--muted');
      }
    });
    attributeUI.mount(this._domAttributes);
    return attributeUI;
  };

  PropertiesDialog.prototype._addDOMEventListeners = function() {
    var selectTab, validateCode;
    PropertiesDialog.__super__._addDOMEventListeners.call(this);
    selectTab = (function(_this) {
      return function(selected) {
        var i, len, selectedCap, tab, tabCap, tabs;
        tabs = ['attributes', 'code', 'styles'];
        for (i = 0, len = tabs.length; i < len; i++) {
          tab = tabs[i];
          if (tab === selected) {
            continue;
          }
          tabCap = tab.charAt(0).toUpperCase() + tab.slice(1);
          ContentEdit.removeCSSClass(_this._domElement, "ct-properties-dialog--" + tab);
          ContentEdit.removeCSSClass(_this["_dom" + tabCap + "Tab"], 'ct-control--active');
        }
        selectedCap = selected.charAt(0).toUpperCase() + selected.slice(1);
        ContentEdit.addCSSClass(_this._domElement, "ct-properties-dialog--" + selected);
        ContentEdit.addCSSClass(_this["_dom" + selectedCap + "Tab"], 'ct-control--active');
        return window.localStorage.setItem('ct-properties-dialog-tab', selected);
      };
    })(this);
    this._domStylesTab.addEventListener('mousedown', (function(_this) {
      return function() {
        return selectTab('styles');
      };
    })(this));
    this._domAttributesTab.addEventListener('mousedown', (function(_this) {
      return function() {
        return selectTab('attributes');
      };
    })(this));
    this._domCodeTab.addEventListener('mousedown', (function(_this) {
      return function() {
        return selectTab('code');
      };
    })(this));
    this._domRemoveAttribute.addEventListener('mousedown', (function(_this) {
      return function(ev) {
        var index, last;
        ev.preventDefault();
        if (_this._focusedAttributeUI) {
          index = _this._attributeUIs.indexOf(_this._focusedAttributeUI);
          last = index === (_this._attributeUIs.length - 1);
          _this._focusedAttributeUI.unmount();
          _this._attributeUIs.splice(index, 1);
          if (last) {
            return _this._addAttributeUI('', '');
          }
        }
      };
    })(this));
    validateCode = (function(_this) {
      return function(ev) {
        var content, error;
        try {
          content = new HTMLString.String(_this._domInnerHTML.value);
          ContentEdit.removeCSSClass(_this._domInnerHTML, 'ct-properties-dialog__inner-html--invalid');
          return ContentEdit.removeCSSClass(_this._domApply, 'ct-control--muted');
        } catch (error) {
          ContentEdit.addCSSClass(_this._domInnerHTML, 'ct-properties-dialog__inner-html--invalid');
          return ContentEdit.addCSSClass(_this._domApply, 'ct-control--muted');
        }
      };
    })(this);
    this._domInnerHTML.addEventListener('input', validateCode);
    this._domInnerHTML.addEventListener('propertychange', validateCode);
    return this._domApply.addEventListener('click', (function(_this) {
      return function(ev) {
        var cssClass;
        ev.preventDefault();
        cssClass = _this._domApply.getAttribute('class');
        if (cssClass.indexOf('ct-control--muted') === -1) {
          return _this.save();
        }
      };
    })(this));
  };

  return PropertiesDialog;

})(ContentTools.DialogUI);

StyleUI = (function(superClass) {
  extend(StyleUI, superClass);

  function StyleUI(style1, applied) {
    this.style = style1;
    StyleUI.__super__.constructor.call(this);
    this._applied = applied;
  }

  StyleUI.prototype.applied = function(applied) {
    if (applied === void 0) {
      return this._applied;
    }
    if (this._applied === applied) {
      return;
    }
    this._applied = applied;
    if (this._applied) {
      return ContentEdit.addCSSClass(this._domElement, 'ct-section--applied');
    } else {
      return ContentEdit.removeCSSClass(this._domElement, 'ct-section--applied');
    }
  };

  StyleUI.prototype.mount = function(domParent, before) {
    var label;
    if (before == null) {
      before = null;
    }
    this._domElement = this.constructor.createDiv(['ct-section']);
    if (this._applied) {
      ContentEdit.addCSSClass(this._domElement, 'ct-section--applied');
    }
    label = this.constructor.createDiv(['ct-section__label']);
    label.textContent = this.style.name();
    this._domElement.appendChild(label);
    this._domElement.appendChild(this.constructor.createDiv(['ct-section__switch']));
    return StyleUI.__super__.mount.call(this, domParent, before);
  };

  StyleUI.prototype._addDOMEventListeners = function() {
    var toggleSection;
    toggleSection = (function(_this) {
      return function(ev) {
        ev.preventDefault();
        if (_this.applied()) {
          return _this.applied(false);
        } else {
          return _this.applied(true);
        }
      };
    })(this);
    return this._domElement.addEventListener('click', toggleSection);
  };

  return StyleUI;

})(ContentTools.AnchoredComponentUI);

AttributeUI = (function(superClass) {
  extend(AttributeUI, superClass);

  function AttributeUI(name, value) {
    AttributeUI.__super__.constructor.call(this);
    this._initialName = name;
    this._initialValue = value;
  }

  AttributeUI.prototype.name = function() {
    return this._domName.value.trim();
  };

  AttributeUI.prototype.value = function() {
    return this._domValue.value.trim();
  };

  AttributeUI.prototype.mount = function(domParent, before) {
    if (before == null) {
      before = null;
    }
    this._domElement = this.constructor.createDiv(['ct-attribute']);
    this._domName = document.createElement('input');
    this._domName.setAttribute('class', 'ct-attribute__name');
    this._domName.setAttribute('name', 'name');
    this._domName.setAttribute('placeholder', ContentEdit._('Name'));
    this._domName.setAttribute('type', 'text');
    this._domName.setAttribute('value', this._initialName);
    this._domElement.appendChild(this._domName);
    this._domValue = document.createElement('input');
    this._domValue.setAttribute('class', 'ct-attribute__value');
    this._domValue.setAttribute('name', 'value');
    this._domValue.setAttribute('placeholder', ContentEdit._('Value'));
    this._domValue.setAttribute('type', 'text');
    this._domValue.setAttribute('value', this._initialValue);
    this._domElement.appendChild(this._domValue);
    return AttributeUI.__super__.mount.call(this, domParent, before);
  };

  AttributeUI.prototype.valid = function(valid) {
    if (valid) {
      return ContentEdit.removeCSSClass(this._domName, 'ct-attribute__name--invalid');
    } else {
      return ContentEdit.addCSSClass(this._domName, 'ct-attribute__name--invalid');
    }
  };

  AttributeUI.prototype._addDOMEventListeners = function() {
    this._domName.addEventListener('blur', (function(_this) {
      return function() {
        var name, nextDomAttribute, nextNameDom;
        name = _this.name();
        nextDomAttribute = _this._domElement.nextSibling;
        _this.trigger('blur');
        if (name === '' && nextDomAttribute) {
          nextNameDom = nextDomAttribute.querySelector('.ct-attribute__name');
          return nextNameDom.focus();
        }
      };
    })(this));
    this._domName.addEventListener('focus', (function(_this) {
      return function() {
        return _this.trigger('focus');
      };
    })(this));
    this._domName.addEventListener('input', (function(_this) {
      return function() {
        return _this.trigger('namechange');
      };
    })(this));
    this._domName.addEventListener('keydown', (function(_this) {
      return function(ev) {
        if (ev.keyCode === 13) {
          return _this._domValue.focus();
        }
      };
    })(this));
    this._domValue.addEventListener('blur', (function(_this) {
      return function() {
        return _this.trigger('blur');
      };
    })(this));
    this._domValue.addEventListener('focus', (function(_this) {
      return function() {
        return _this.trigger('focus');
      };
    })(this));
    return this._domValue.addEventListener('keydown', (function(_this) {
      return function(ev) {
        var nextDomAttribute, nextNameDom;
        if (ev.keyCode !== 13 && (ev.keyCode !== 9 || ev.shiftKey)) {
          return;
        }
        ev.preventDefault();
        nextDomAttribute = _this._domElement.nextSibling;
        if (!nextDomAttribute) {
          _this._domValue.blur();
          nextDomAttribute = _this._domElement.nextSibling;
        }
        if (nextDomAttribute) {
          nextNameDom = nextDomAttribute.querySelector('.ct-attribute__name');
          return nextNameDom.focus();
        }
      };
    })(this));
  };

  return AttributeUI;

})(ContentTools.AnchoredComponentUI);
