// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ContentTools.TableDialog = (function(superClass) {
  extend(TableDialog, superClass);

  function TableDialog(table) {
    this.table = table;
    if (this.table) {
      TableDialog.__super__.constructor.call(this, 'Update table');
    } else {
      TableDialog.__super__.constructor.call(this, 'Insert table');
    }
  }

  TableDialog.prototype.mount = function() {
    var cfg, domBodyLabel, domControlGroup, domFootLabel, domHeadLabel, footCSSClasses, headCSSClasses;
    TableDialog.__super__.mount.call(this);
    cfg = {
      columns: 3,
      foot: false,
      head: true
    };
    if (this.table) {
      cfg = {
        columns: this.table.firstSection().children[0].children.length,
        foot: this.table.tfoot(),
        head: this.table.thead()
      };
    }
    ContentEdit.addCSSClass(this._domElement, 'ct-table-dialog');
    ContentEdit.addCSSClass(this._domView, 'ct-table-dialog__view');
    headCSSClasses = ['ct-section'];
    if (cfg.head) {
      headCSSClasses.push('ct-section--applied');
    }
    this._domHeadSection = this.constructor.createDiv(headCSSClasses);
    this._domView.appendChild(this._domHeadSection);
    domHeadLabel = this.constructor.createDiv(['ct-section__label']);
    domHeadLabel.textContent = ContentEdit._('Table head');
    this._domHeadSection.appendChild(domHeadLabel);
    this._domHeadSwitch = this.constructor.createDiv(['ct-section__switch']);
    this._domHeadSection.appendChild(this._domHeadSwitch);
    this._domBodySection = this.constructor.createDiv(['ct-section', 'ct-section--applied', 'ct-section--contains-input']);
    this._domView.appendChild(this._domBodySection);
    domBodyLabel = this.constructor.createDiv(['ct-section__label']);
    domBodyLabel.textContent = ContentEdit._('Table body (columns)');
    this._domBodySection.appendChild(domBodyLabel);
    this._domBodyInput = document.createElement('input');
    this._domBodyInput.setAttribute('class', 'ct-section__input');
    this._domBodyInput.setAttribute('maxlength', '2');
    this._domBodyInput.setAttribute('name', 'columns');
    this._domBodyInput.setAttribute('type', 'text');
    this._domBodyInput.setAttribute('value', cfg.columns);
    this._domBodySection.appendChild(this._domBodyInput);
    footCSSClasses = ['ct-section'];
    if (cfg.foot) {
      footCSSClasses.push('ct-section--applied');
    }
    this._domFootSection = this.constructor.createDiv(footCSSClasses);
    this._domView.appendChild(this._domFootSection);
    domFootLabel = this.constructor.createDiv(['ct-section__label']);
    domFootLabel.textContent = ContentEdit._('Table foot');
    this._domFootSection.appendChild(domFootLabel);
    this._domFootSwitch = this.constructor.createDiv(['ct-section__switch']);
    this._domFootSection.appendChild(this._domFootSwitch);
    domControlGroup = this.constructor.createDiv(['ct-control-group', 'ct-control-group--right']);
    this._domControls.appendChild(domControlGroup);
    this._domApply = this.constructor.createDiv(['ct-control', 'ct-control--text', 'ct-control--apply']);
    this._domApply.textContent = 'Apply';
    domControlGroup.appendChild(this._domApply);
    return this._addDOMEventListeners();
  };

  TableDialog.prototype.save = function() {
    var footCSSClass, headCSSClass, tableCfg;
    footCSSClass = this._domFootSection.getAttribute('class');
    headCSSClass = this._domHeadSection.getAttribute('class');
    tableCfg = {
      columns: parseInt(this._domBodyInput.value),
      foot: footCSSClass.indexOf('ct-section--applied') > -1,
      head: headCSSClass.indexOf('ct-section--applied') > -1
    };
    return this.trigger('save', tableCfg);
  };

  TableDialog.prototype.unmount = function() {
    TableDialog.__super__.unmount.call(this);
    this._domBodyInput = null;
    this._domBodySection = null;
    this._domApply = null;
    this._domHeadSection = null;
    this._domHeadSwitch = null;
    this._domFootSection = null;
    return this._domFootSwitch = null;
  };

  TableDialog.prototype._addDOMEventListeners = function() {
    var toggleSection;
    TableDialog.__super__._addDOMEventListeners.call(this);
    toggleSection = function(ev) {
      ev.preventDefault();
      if (this.getAttribute('class').indexOf('ct-section--applied') > -1) {
        return ContentEdit.removeCSSClass(this, 'ct-section--applied');
      } else {
        return ContentEdit.addCSSClass(this, 'ct-section--applied');
      }
    };
    this._domHeadSection.addEventListener('click', toggleSection);
    this._domFootSection.addEventListener('click', toggleSection);
    this._domBodySection.addEventListener('click', (function(_this) {
      return function(ev) {
        return _this._domBodyInput.focus();
      };
    })(this));
    this._domBodyInput.addEventListener('input', (function(_this) {
      return function(ev) {
        var valid;
        valid = /^[1-9]\d{0,1}$/.test(ev.target.value);
        if (valid) {
          ContentEdit.removeCSSClass(_this._domBodyInput, 'ct-section__input--invalid');
          return ContentEdit.removeCSSClass(_this._domApply, 'ct-control--muted');
        } else {
          ContentEdit.addCSSClass(_this._domBodyInput, 'ct-section__input--invalid');
          return ContentEdit.addCSSClass(_this._domApply, 'ct-control--muted');
        }
      };
    })(this));
    return this._domApply.addEventListener('click', (function(_this) {
      return function(ev) {
        var cssClass;
        ev.preventDefault();
        cssClass = _this._domApply.getAttribute('class');
        if (cssClass.indexOf('ct-control--muted') === -1) {
          return _this.save();
        }
      };
    })(this));
  };

  return TableDialog;

})(ContentTools.DialogUI);
