// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ContentEdit.Region = (function(superClass) {
  extend(Region, superClass);

  function Region(domElement) {
    var c, childNode, childNodes, cls, element, i, len, tagNames;
    Region.__super__.constructor.call(this);
    this._domElement = domElement;
    tagNames = ContentEdit.TagNames.get();
    childNodes = (function() {
      var i, len, ref, results;
      ref = this._domElement.childNodes;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        c = ref[i];
        results.push(c);
      }
      return results;
    }).call(this);
    for (i = 0, len = childNodes.length; i < len; i++) {
      childNode = childNodes[i];
      if (childNode.nodeType !== 1) {
        continue;
      }
      if (childNode.getAttribute("data-ce-tag")) {
        cls = tagNames.match(childNode.getAttribute("data-ce-tag"));
      } else {
        cls = tagNames.match(childNode.tagName);
      }
      element = cls.fromDOMElement(childNode);
      this._domElement.removeChild(childNode);
      if (element) {
        this.attach(element);
      }
    }
  }

  Region.prototype.domElement = function() {
    return this._domElement;
  };

  Region.prototype.isMounted = function() {
    return true;
  };

  Region.prototype.type = function() {
    return 'Region';
  };

  Region.prototype.html = function(indent) {
    var c;
    if (indent == null) {
      indent = '';
    }
    return ((function() {
      var i, len, ref, results;
      ref = this.children;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        c = ref[i];
        results.push(c.html(indent));
      }
      return results;
    }).call(this)).join('\n').trim();
  };

  return Region;

})(ContentEdit.NodeCollection);
