// Generated by CoffeeScript 1.10.0
describe('`ContentEdit.Region()`', function() {
  return it('should return an instance of Region`', function() {
    var region;
    region = new ContentEdit.Region(document.createElement('div'));
    return expect(region instanceof ContentEdit.Region).toBe(true);
  });
});

describe('`ContentEdit.Region.domElement()`', function() {
  return it('should return the DOM element the region was initialized with', function() {
    var domElement, region;
    domElement = document.createElement('div');
    region = new ContentEdit.Region(domElement);
    return expect(region.domElement()).toBe(domElement);
  });
});

describe('`ContentEdit.Region.isMounted()`', function() {
  return it('should always return true', function() {
    var region;
    region = new ContentEdit.Region(document.createElement('div'));
    return expect(region.isMounted()).toBe(true);
  });
});

describe('`ContentEdit.Region.type()`', function() {
  return it('should return \'Region\'', function() {
    var region;
    region = new ContentEdit.Region(document.createElement('div'));
    return expect(region.type()).toBe('Region');
  });
});

describe('`ContentEdit.Region.html()`', function() {
  return it('should return a HTML string for the region', function() {
    var region;
    region = new ContentEdit.Region(document.createElement('div'));
    region.attach(new ContentEdit.Text('p', {}, 'one'));
    region.attach(new ContentEdit.Text('p', {}, 'two'));
    region.attach(new ContentEdit.Text('p', {}, 'three'));
    return expect(region.html()).toBe('<p>\n' + (ContentEdit.INDENT + "one\n") + '</p>\n' + '<p>\n' + (ContentEdit.INDENT + "two\n") + '</p>\n' + '<p>\n' + (ContentEdit.INDENT + "three\n") + '</p>');
  });
});
