// Generated by CoffeeScript 1.8.0
angular.module('ximdex.common.directive').directive("compileTemplate", function($compile, $parse) {
  return {
    restrict: "A",
    link: function(scope, element, attr) {
      var parsed;
      parsed = $parse(attr.ngBindHtml);
      scope.$watch((function() {
        return (parsed(scope) || "").toString();
      }), function() {
        $compile(element, null, -9999)(scope);
      });
    }
  };
});
