// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("ximdex.common.directive").directive("ximAssocNodes", [
    "xTranslate", "$window", "$http", "xUrlHelper", "xMenu", "$document", "$timeout", "$q", "xTabs", "$rootScope", function(xTranslate, $window, $http, xUrlHelper, xMenu, $document, $timeout, $q, xTabs, $rootScope) {
      var base_url;
      base_url = $window.X.baseUrl;
      return {
        templateUrl: base_url + '/inc/js/angular/templates/ximTree.html',
        restrict: "E",
        replace: true,
        controller: "AssocNodesCtrl",
        controllerAs: "ctrl1"
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=ximAssocNodes.js.map
