// Generated by CoffeeScript 1.8.0
angular.module("ximdex.common.directive").directive("ximResizer", function($document, $timeout) {
  return function($scope, $element, $attrs) {
    var expanded, hidePanel, listenHidePanel, mousemove, mouseup, showPanel, size, togglePanel;
    size = 300;
    expanded = $($attrs.ximResizerToggle).hasClass("hide");
    listenHidePanel = true;
    mousemove = function(event) {
      var x;
      x = event.pageX;
      if (x > $document.width() - 17) {
        x = $document.width() - 17;
      }
      if ($attrs.ximResizerMin && x < $attrs.ximResizerMin) {
        x = parseInt($attrs.ximResizerMin);
      }
      $element.css({
        left: x + "px"
      });
      $($attrs.ximResizerLeft).css({
        width: x + "px"
      });
      $($attrs.ximResizerRight).css({
        left: (x + parseInt($attrs.ximResizerWidth)) + "px"
      });
    };
    mouseup = function() {
      $document.unbind("mousemove", mousemove);
      $document.unbind("mouseup", mouseup);
    };
    $element.on("mousedown", function(event) {
      if (expanded) {
        event.preventDefault();
        $document.on("mousemove", mousemove);
        $document.on("mouseup", mouseup);
      }
    });
    hidePanel = function() {
      var a, b;
      if (!expanded && listenHidePanel) {
        a = 7;
        b = parseInt($attrs.ximResizerWidth) + a;
        $($attrs.ximResizerLeft).css({
          left: (-size - 7) + "px"
        });
        $($attrs.ximResizerRight).css({
          left: (b - 7) + "px"
        });
        $timeout(function() {
          return listenHidePanel = false;
        }, 500);
      }
    };
    showPanel = function() {
      if (!expanded && !listenHidePanel) {
        $($attrs.ximResizerLeft).css({
          left: 0 + "px"
        });
        $($attrs.ximResizerRight).css({
          left: (size + parseInt($attrs.ximResizerWidth) + 7) + "px"
        });
        $timeout(function() {
          return listenHidePanel = true;
        }, 500);
      }
    };
    $element.on("mouseenter", showPanel);
    $($attrs.ximResizerLeft).on("mouseleave", hidePanel);
    togglePanel = function(event) {
      $(this).toggleClass("hide");
      $(this).toggleClass("tie");
      $($attrs.ximResizerLeft).toggleClass("hideable");
      $($attrs.ximResizerRight).toggleClass("hideable");
      $element.toggleClass("hideable");
      expanded = !expanded;
      size = $($attrs.ximResizerLeft).width();
      if (!expanded) {
        hidePanel();
      }
    };
    $($attrs.ximResizerToggle).on("click", togglePanel);
  };
});
