// Generated by CoffeeScript 1.10.0
ContentTools.History = (function() {
  function History(regions) {
    this._lastSnapshotTaken = null;
    this._regions = {};
    this.replaceRegions(regions);
    this._snapshotIndex = -1;
    this._snapshots = [];
    this._store();
  }

  History.prototype.canRedo = function() {
    return this._snapshotIndex < this._snapshots.length - 1;
  };

  History.prototype.canUndo = function() {
    return this._snapshotIndex > 0;
  };

  History.prototype.index = function() {
    return this._snapshotIndex;
  };

  History.prototype.length = function() {
    return this._snapshots.length;
  };

  History.prototype.snapshot = function() {
    return this._snapshots[this._snapshotIndex];
  };

  History.prototype.goTo = function(index) {
    this._snapshotIndex = Math.min(this._snapshots.length - 1, Math.max(0, index));
    return this.snapshot();
  };

  History.prototype.redo = function() {
    return this.goTo(this._snapshotIndex + 1);
  };

  History.prototype.replaceRegions = function(regions) {
    var k, results, v;
    this._regions = {};
    results = [];
    for (k in regions) {
      v = regions[k];
      results.push(this._regions[k] = v);
    }
    return results;
  };

  History.prototype.restoreSelection = function(snapshot) {
    var element, region;
    if (!snapshot.selected) {
      return;
    }
    region = this._regions[snapshot.selected.region];
    element = region.descendants()[snapshot.selected.element];
    element.focus();
    if (element.selection && snapshot.selected.selection) {
      return element.selection(snapshot.selected.selection);
    }
  };

  History.prototype.stopWatching = function() {
    if (this._watchInterval) {
      clearInterval(this._watchInterval);
    }
    if (this._delayedStoreTimeout) {
      return clearTimeout(this._delayedStoreTimeout);
    }
  };

  History.prototype.undo = function() {
    return this.goTo(this._snapshotIndex - 1);
  };

  History.prototype.watch = function() {
    var watch;
    this._lastSnapshotTaken = Date.now();
    watch = (function(_this) {
      return function() {
        var delayedStore, lastModified;
        lastModified = ContentEdit.Root.get().lastModified();
        if (lastModified === null) {
          return;
        }
        if (lastModified > _this._lastSnapshotTaken) {
          if (_this._delayedStoreRequested === lastModified) {
            return;
          }
          if (_this._delayedStoreTimeout) {
            clearTimeout(_this._delayedStoreTimeout);
          }
          delayedStore = function() {
            _this._lastSnapshotTaken = lastModified;
            return _this._store();
          };
          _this._delayedStoreRequested = lastModified;
          return _this._delayedStoreTimeout = setTimeout(delayedStore, 500);
        }
      };
    })(this);
    return this._watchInterval = setInterval(watch, 50);
  };

  History.prototype._store = function() {
    var element, name, other_region, ref, ref1, region, snapshot;
    snapshot = {
      regions: {},
      selected: null
    };
    ref = this._regions;
    for (name in ref) {
      region = ref[name];
      snapshot.regions[name] = region.html();
    }
    element = ContentEdit.Root.get().focused();
    if (element) {
      snapshot.selected = {};
      region = element.closest(function(node) {
        return node.type() === 'Region';
      });
      if (!region) {
        return;
      }
      ref1 = this._regions;
      for (name in ref1) {
        other_region = ref1[name];
        if (region === other_region) {
          snapshot.selected.region = name;
          break;
        }
      }
      snapshot.selected.element = region.descendants().indexOf(element);
      if (element.selection) {
        snapshot.selected.selection = element.selection();
      }
    }
    if (this._snapshotIndex < (this._snapshots.length - 1)) {
      this._snapshots = this._snapshots.slice(0, this._snapshotIndex + 1);
    }
    this._snapshotIndex++;
    return this._snapshots.splice(this._snapshotIndex, 0, snapshot);
  };

  return History;

})();
