#!/bin/bash

XIMDEX_PASS="${XIMDEX_PASS:=ximdex}"
#HOSTNAME="${HOSTNAME:=localhost}" # da un numero raro en db
if [ "$HOSTNAME" -eq "85bc26a0e200" ]
then
	HOSTNAME="localhost"
fi
PORT="${PORT:=5000}"

service mysql start

mysql -u root -pximdex ximdex -e "UPDATE Config SET ConfigValue='http://$HOSTNAME:$PORT' WHERE ConfigKEY='UrlRoot'; UPDATE Users SET Pass=MD5('$XIMDEX_PASS') where IdUser = '301';"

service mysql stop

supervisord -n


