// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ContentTools.ConfirmPublishDialog = (function(superClass) {
  extend(ConfirmPublishDialog, superClass);

  function ConfirmPublishDialog() {
    ConfirmPublishDialog.__super__.constructor.call(this, 'Se va a proceder a publicar los cambios.');
    this._state = 'populated';
  }

  ConfirmPublishDialog.prototype.mount = function() {
    var domActions, domTools;
    ConfirmPublishDialog.__super__.mount.call(this);
    ContentEdit.addCSSClass(this._domElement, 'ct-confirm-dialog');
    ContentEdit.addCSSClass(this._domView, 'ct-confirm-dialog__view');
    domTools = this.constructor.createDiv(['ct-control-group', 'ct-control-group--left']);
    this._domControls.appendChild(domTools);
    this._domInfo = this.constructor.createDiv(['ct-info']);
    this._domInfo.textContent = ContentEdit._('¿Desea continuar?');
    this._domView.appendChild(this._domInfo);
    domActions = this.constructor.createDiv(['ct-control-group', 'ct-control-group--right']);
    this._domControls.appendChild(domActions);
    this._domOK = this.constructor.createDiv(['ct-control', 'ct-control--text', 'ct-control--upload']);
    this._domOK.textContent = ContentEdit._('Continuar');
    domActions.appendChild(this._domOK);
    this._domCancel = this.constructor.createDiv(['ct-control', 'ct-control--text', 'ct-control--cancel']);
    this._domCancel.textContent = ContentEdit._('Cancelar');
    domActions.appendChild(this._domCancel);
    this._addDOMEventListeners();
    return this.trigger('ConfirmPublishDialog.mount');
  };

  ConfirmPublishDialog.prototype._addDOMEventListeners = function() {
    ConfirmPublishDialog.__super__._addDOMEventListeners.call(this);
    this._domCancel.addEventListener('click', (function(_this) {
      return function(ev) {
        return _this.trigger('cancel');
      };
    })(this));
    return this._domOK.addEventListener('click', (function(_this) {
      return function(ev) {
        return _this.trigger('ok');
      };
    })(this));
  };

  return ConfirmPublishDialog;

})(ContentTools.DialogUI);
