// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ContentTools.ModalUI = (function(superClass) {
  extend(ModalUI, superClass);

  function ModalUI(transparent, allowScrolling) {
    ModalUI.__super__.constructor.call(this);
    this._transparent = transparent;
    this._allowScrolling = allowScrolling;
  }

  ModalUI.prototype.mount = function() {
    this._domElement = this.constructor.createDiv(['ct-widget', 'ct-modal']);
    this.parent().domElement().appendChild(this._domElement);
    if (this._transparent) {
      this.addCSSClass('ct-modal--transparent');
    }
    if (!this._allowScrolling) {
      ContentEdit.addCSSClass(document.body, 'ct--no-scroll');
    }
    return this._addDOMEventListeners();
  };

  ModalUI.prototype.unmount = function() {
    if (!this._allowScrolling) {
      ContentEdit.removeCSSClass(document.body, 'ct--no-scroll');
    }
    return ModalUI.__super__.unmount.call(this);
  };

  ModalUI.prototype._addDOMEventListeners = function() {
    return this._domElement.addEventListener('click', (function(_this) {
      return function(ev) {
        return _this.trigger('click');
      };
    })(this));
  };

  return ModalUI;

})(ContentTools.WidgetUI);
