<?php
/*
 *
 * WARNING: Do not edit this file by hand, automatically generated.
 *
 *
 */


/**
 * XIMDEX_ROOT_PATH
 */
if (!defined('XIMDEX_ROOT_PATH'))
	define('XIMDEX_ROOT_PATH', realpath(dirname(__FILE__) . '/../../../'));

include_once (XIMDEX_ROOT_PATH . '/inc/helper/GenericData.class.php');

class RelNodeMetaData_ORM extends GenericData   {
	var $_idField = 'IdNode';
	var $_table = 'RelNodeMetaData';
	var $_metaData = array(
				'IdNode' => array('type' => "int(12)", 'not_null' => 'true', 'primary_key' => true),
				'IdMetaData' => array('type' => "int(12)", 'not_null' => 'true')
				);
	var $_uniqueConstraints = array(

				);
	var $_indexes = array('IdNode');
	var $IdNode = 0;
	var $IdMetaData = 0;
}
?>
